[tool.poetry]
name = "clinical_informatics_umls"
version = "0.1.0"
description = ""
authors = ["rcolinp <rcolinpiombino@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8,<3.11"
pandas = "^1.3.2"
numpy = "^1.21.2"
psycopg2 = "^2.9.1"
SQLAlchemy = "^1.4.23"
getpass2 = "^1.0.2"
neo4j = "^4.3.4"
py2neo = "^2021.2.0"
jupyter = "^1.0.0"
ipykernel = "^6.4.0"
notebook = "^6.4.3"
nbconvert = "^6.1.0"
mysql-connector = "^2.2.9"
pysqlite3 = "^0.4.6"
neo4j-driver = "^4.3.4"
matplotlib = "^3.4.3"
sklearn = "^0.0"
ipython-cypher = "^0.2.6"
opencypher = "^0.3.0"
jedi = "0.18.0"
networkx = "^2.6.3"
pyvis = "^0.1.9"
pyarrow = "^5.0.0"
fastparquet = "^0.7.1"
parquet = "^1.3.1"

[tool.poetry.dev-dependencies]
pyproject-toml = "^0.0.11"
toml = "^0.10.2"
autopep8 = "^1.5.7"
black = "^21.8b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
