[tool.poetry]
name = "clinical_informatics_umls"
version = "0.1.0"
description = ""
authors = ["rcolinp <rcolinpiombino@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8,<3.11"
pandas = "^1.3.2"
numpy = "^1.21.2"
SQLAlchemy = "^1.4.23"
getpass2 = "^1.0.2"
neo4j = "^4.3.4"
py2neo = "^2021.2.0"
jupyter = "^1.0.0"
ipykernel = "^6.4.0"
notebook = "^6.4.3"
nbconvert = "^6.1.0"
mysql-connector = "^2.2.9"
pysqlite3 = "^0.4.6"
neo4j-driver = "^4.3.4"
matplotlib = "^3.4.3"
sklearn = "^0.0"
ipython-cypher = "^0.2.6"
opencypher = "^0.3.0"
jedi = "0.18.0"
pyarrow = "^5.0.0"
fastparquet = "^0.7.1"
parquet = "^1.3.1"
ipywidgets = "^7.6.5"
ipython = {extras = ["all"], version = "^7.27.0"}
docker = "^5.0.2"
jupyter-client = "^7.0.3"
docker-compose = "^1.29.2"
compose = "^1.2.5"
PyMySQL = "^1.0.2"
mariadb = "^1.0.7"
psycopg2-binary = "^2.9.1"
networkx = "^2.6.3"
python-igraph = "^0.9.6"
jupyterlab = "^3.1.14"
neo4jrestclient = "^2.1.1"
neographviz = "^0.4.6"
pyvis = "^0.1.9"
tqdm = "^4.62.3"
lxml = "^4.6.3"
graphviz = "^0.17"

[tool.poetry.dev-dependencies]
pyproject-toml = "^0.0.11"
toml = "^0.10.2"
autopep8 = "^1.5.7"
black = "^21.8b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
