[tool.poetry]
name = "clinical_informatics_umls"
version = "0.1.0"
description = ""
authors = ["rcolinp <rcolinpiombino@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8,<3.11"
pandas = "^1.3.2"
numpy = "^1.21.2"
psycopg2 = "^2.9.1"
SQLAlchemy = "^1.4.23"
getpass2 = "^1.0.2"
neo4j = "^4.3.4"
py2neo = "^2021.2.0"
jupyter = "^1.0.0"
ipykernel = "^6.4.0"
notebook = "^6.4.3"
nbconvert = "^6.1.0"
mysql-connector = "^2.2.9"
pysqlite3 = "^0.4.6"

[tool.poetry.dev-dependencies]
pyproject-toml = "^0.0.11"
toml = "^0.10.2"
autopep8 = "^1.5.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
