[tool.poetry]
name = "clinical_informatics_umls"
version = "0.1.0"
description = ""
authors = ["rcolinp <rcolinpiombino@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8,<3.10"
pandas = "^1.3.2"
numpy = "^1.21.2"
SQLAlchemy = "^1.4.23"
getpass2 = "^1.0.2"
neo4j = "^4.3.4"
py2neo = "^2021.2.0"
mysql-connector = "^2.2.9"
jedi = "0.18.0"
docker = "^5.0.2"
PyMySQL = "^1.0.2"
mariadb = "^1.0.7"
psycopg2-binary = "^2.9.1"
networkx = "^2.6.3"
rdflib = "5.0.0"
requests = "^2.26.0"
pysqlite3 = "^0.4.6"
PyLD = "^2.0.3"
neographviz = "^0.4.6"
pyvis = "^0.1.9"
ipyradiant = "^0.2.0"

[tool.poetry.dev-dependencies]
pyproject-toml = "^0.0.11"
toml = "^0.10.2"
autopep8 = "^1.5.7"
black = "^21.8b0"
tox = "^3.24.4"
flake8 = "^4.0.1"
typing-extensions = "^3.10.0"
python-dotenv = "^0.19.1"
jupyterlab = "^3.2.0"
ipython = "^7.28.0"
ipywidgets = "^7.6.5"
nbconvert = "^6.2.0"
notebook = "^6.4.5"
ipykernel = "^6.4.2"
jupyter = "^1.0.0"
jupyter-client = "^7.0.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
