[tool.poetry]
name = "clinical_informatics_umls"
version = "0.1.0"
description = ""
authors = ["rcolinp <rcolinpiombino@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
pandas = "^1.3.4"
SQLAlchemy = "^1.4.23"
getpass2 = "^1.0.2"
neo4j = "^4.3.4"
py2neo = "^2021.2.0"
requests = "^2.26.0"
pysqlite3 = "^0.4.6"
neographviz = "^0.4.6"
neo4jupyter = "^0.2.0"
mariadb = "^1.0.8"
PyMySQL = "^1.0.2"
psycopg2-binary = "^2.9.2"
rdflib = "^6.1.1"
matplotlib = "^3.5.0"
ipyradiant = "^0.2.0"
lxml = "^4.6.3"
pyvis = "^0.1.9"
numpy = "^1.20.3"
pronto = "^2.4.4"
SPARQLWrapper = "^1.8.5"
sparql-dataframe = "^0.4"
tqdm = "^4.62.3"

[tool.poetry.dev-dependencies]
typing-extensions = "^3.10.0"
ipykernel = "^6.5.1"
autopep8 = "^1.6.0"
toml = "^0.10.2"
jupyter = "^1.0.0"
python-dotenv = "^0.19.2"
pyproject-toml = "^0.0.11"
pylint = "^2.12.2"
sqlparse = "^0.4.2"
black = "^22.1.0"
isort = "^5.10.1"
mypy = "^0.931"
flake8 = "^4.0.1"
tox = "^3.24.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# https://pycqa.github.io/isort/docs/configuration/config_files.html
[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88