[tool.poetry]
name = "clinical_informatics_umls"
version = "0.1.0"
description = ""
authors = ["rcolinp <rcolinpiombino@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
pandas = "^1.3.1"
numpy = "^1.20.0"
SQLAlchemy = "^1.4.23"
getpass2 = "^1.0.2"
neo4j = "^4.3.4"
py2neo = "^2021.2.0"
jedi = "0.18.0"
requests = "^2.22.0"
pysqlite3 = "^0.4.6"
neographviz = "^0.4.6"
neo4jupyter = "^0.2.0"
mariadb = "^1.0.8"
PyMySQL = "^1.0.2"
psycopg2-binary = "^2.9.2"
rdflib = "^6.0.2"
mysql-connector = "^2.2.9"
matplotlib = "^3.5.0"
ipyradiant = "^0.2.0"
Owlready2 = "^0.35"
lxml = "^4.6.4"
pyvis = "^0.1.9"
mysql-connector-python = "^8.0.27"

[tool.poetry.dev-dependencies]
typing-extensions = "^3.10.0"
notebook = "^6.4.6"
ipykernel = "^6.5.1"
autopep8 = "^1.6.0"
toml = "^0.10.2"
jupyter = "^1.0.0"
ipywidgets = "^7.6.5"
pip = "^21.3.1"
python-dotenv = "^0.19.2"
docker-compose = "^1.29.2"
jupyterlab = "^3.2.4"
flake8 = "^4.0.1"
tox = "^3.24.4"
twine = "^3.7.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"